runtime: nodejs20

env_variables:
  DB_HOST: '104.197.180.231'
  DB_USER: 'cartbutler8946'
  DB_PASSWORD: 'conestoga8946'
  DB_NAME: 'cartbutler8946'
  DATABASE_URL: 'postgresql://cartbutler8946:conestoga8946@104.197.180.231:5432/cartbutler8946'